# Generated by Django 6.0.2 on 2026-03-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Viikon aloituspäivä (maanantai).', unique=True)),
                ('title', models.CharField(blank=True, help_text='Vapaaehtoinen otsikko viikolle.', max_length=120)),
            ],
            options={
                'verbose_name': 'Viikkosuunnitelma',
                'verbose_name_plural': 'Viikkosuunnitelmat',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Ma'), (1, 'Ti'), (2, 'Ke'), (3, 'To'), (4, 'Pe'), (5, 'La'), (6, 'Su')])),
                ('planned_workout', models.CharField(choices=[('A', 'Punttisali, ohjelma 1'), ('B', 'Punttisali, ohjelma 2'), ('C', 'Juoksu, pitkä'), ('D', 'Juoksu, intervalli'), ('E', 'Kävely, pitkä'), ('F', 'Kävely, palauttava/kevyt'), ('G', 'Lepopäivä')], max_length=1)),
                ('week_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tracker.weekplan')),
            ],
            options={
                'verbose_name': 'Suunnitelmapäivä',
                'verbose_name_plural': 'Suunnitelmapäivät',
                'ordering': ['week_plan__week_start_date', 'weekday'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('workout', models.CharField(choices=[('A', 'Punttisali, ohjelma 1'), ('B', 'Punttisali, ohjelma 2'), ('C', 'Juoksu, pitkä'), ('D', 'Juoksu, intervalli'), ('E', 'Kävely, pitkä'), ('F', 'Kävely, palauttava/kevyt'), ('G', 'Lepopäivä')], max_length=1)),
                ('completed', models.BooleanField(default=False, help_text='Toteutuiko treeni? (Kyllä/Ei)')),
                ('notes', models.TextField(blank=True)),
                ('planned_day', models.ForeignKey(blank=True, help_text='Valinnainen linkki suunnitelmapäivään (voi olla tyhjä, jos toteuma ei ollut suunnitelmassa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tracker.planday')),
            ],
            options={
                'verbose_name': 'Toteuma',
                'verbose_name_plural': 'Toteumat',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='planday',
            constraint=models.UniqueConstraint(fields=('week_plan', 'weekday'), name='unique_plan_day_per_week'),
        ),
    ]
