# Generated by Django 6.0.2 on 2026-03-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planday',
            name='planned_workout',
            field=models.CharField(choices=[('A', 'Punttisali, ohjelma 1'), ('B', 'Punttisali, ohjelma 2'), ('C', 'Juoksu, pitkä'), ('D', 'Juoksu, intervalli'), ('E', 'Kävely, pitkä'), ('F', 'Kävely, palauttava/kevyt'), ('G', 'Lepopäivä')], max_length=1, verbose_name='Suunniteltu treeni'),
        ),
        migrations.AlterField(
            model_name='planday',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ma'), (1, 'Ti'), (2, 'Ke'), (3, 'To'), (4, 'Pe'), (5, 'La'), (6, 'Su')], verbose_name='Viikonpäivä'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='title',
            field=models.CharField(blank=True, help_text='Vapaaehtoinen otsikko viikolle.', max_length=120, verbose_name='Otsikko'),
        ),
        migrations.AlterField(
            model_name='weekplan',
            name='week_start_date',
            field=models.DateField(help_text='Viikon aloituspäivä (maanantai).', unique=True, verbose_name='Viikon aloituspäivä'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='completed',
            field=models.BooleanField(default=False, help_text='Toteutuiko treeni? (Kyllä/Ei)', verbose_name='Toteutui'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(unique=True, verbose_name='Päivämäärä'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Muistiinpanot'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='planned_day',
            field=models.ForeignKey(blank=True, help_text='Valinnainen linkki suunnitelmapäivään (voi olla tyhjä, jos toteuma ei ollut suunnitelmassa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tracker.planday', verbose_name='Suunnitelmapäivä'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='workout',
            field=models.CharField(choices=[('A', 'Punttisali, ohjelma 1'), ('B', 'Punttisali, ohjelma 2'), ('C', 'Juoksu, pitkä'), ('D', 'Juoksu, intervalli'), ('E', 'Kävely, pitkä'), ('F', 'Kävely, palauttava/kevyt'), ('G', 'Lepopäivä')], max_length=1, verbose_name='Treeni'),
        ),
    ]
